# Generated by Django 3.2.5 on 2021-08-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='service.categorymodel'),
            preserve_default=False,
        ),
    ]
