# Generated by Django 3.2.5 on 2021-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
