# Generated by Django 3.2.5 on 2021-08-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
