# Generated by Django 3.2.5 on 2021-08-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.addressmodels'),
            preserve_default=False,
        ),
    ]
