# Generated by Django 3.2.5 on 2021-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_pid_ordermodel_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order',
            field=models.CharField(blank=True, choices=[('one', 'one1'), ('two', 'two2'), ('three', 'three2')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AddressModels',
        ),
    ]
