# Generated by Django 3.2.5 on 2021-08-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210808_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
